version: '3.8'

services:
  api:
    build:
      context: ./Monitoring-and-Logging
    ports:
      - "8000:8000"
      - "8001:8001"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Monitoring-and-Logging/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3030:3000"
    depends_on:
      - prometheus
